import { ALL_PERMISSIONS } from './permissions';

export interface RoleDefinition {
  id: string;
  name: string;
  department: RoleDepartment;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  description: string;
  isOwnerRole?: boolean;
  defaultPermissions: string[];
}

export type RoleDepartment =
  | 'Direction & Fondateurs'
  | 'Opérations & Logistique'
  | 'Service Client & Vente'
  | 'Marketing & Croissance'
  | 'Finance & Comptabilité'
  | 'Ressources Humaines & IT'
  | 'Audit & Conseil';

export const ROLE_DEPARTMENTS: RoleDepartment[] = [
  'Direction & Fondateurs',
  'Opérations & Logistique',
  'Service Client & Vente',
  'Marketing & Croissance',
  'Finance & Comptabilité',
  'Ressources Humaines & IT',
  'Audit & Conseil',
];

const ALL_PERMISSION_KEYS = ALL_PERMISSIONS.map((p) => p.key);

export const ALL_ROLES: RoleDefinition[] = [
  // ==========================================
  // 1. DIRECTION & FONDATEURS
  // ==========================================
  {
    id: 'OWNER',
    name: 'Fondateur & Dirigeant (Owner)',
    department: 'Direction & Fondateurs',
    badgeBg: 'bg-amber-500/10',
    badgeText: 'text-amber-500',
    badgeBorder: 'border-amber-500/20',
    description: 'Accès total et irrévocable à toutes les fonctionnalités, finances, paramètres et gestion de l\'équipe.',
    isOwnerRole: true,
    defaultPermissions: ALL_PERMISSION_KEYS,
  },
  {
    id: 'CO_OWNER',
    name: 'Co-Fondateur & Associé',
    department: 'Direction & Fondateurs',
    badgeBg: 'bg-amber-500/10',
    badgeText: 'text-amber-400',
    badgeBorder: 'border-amber-500/20',
    description: 'Co-gérance complète de la maison NAY Parfum avec tous les privilèges d\'administration.',
    isOwnerRole: true,
    defaultPermissions: ALL_PERMISSION_KEYS,
  },
  {
    id: 'GENERAL_MANAGER',
    name: 'Directeur Général',
    department: 'Direction & Fondateurs',
    badgeBg: 'bg-purple-500/10',
    badgeText: 'text-purple-400',
    badgeBorder: 'border-purple-500/20',
    description: 'Supervision globale des opérations, finances, ventes, équipe et décisions stratégiques.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_financials',
      'dashboard.view_operations',
      'dashboard.view_marketing',
      'dashboard.view_support',
      'orders.view',
      'orders.create',
      'orders.edit',
      'orders.change_status',
      'orders.confirm',
      'orders.prepare',
      'orders.cancel',
      'orders.refund',
      'orders.export',
      'orders.manage_attachments',
      'orders.view_sensitive_financials',
      'products.view',
      'products.create',
      'products.edit',
      'products.edit_price',
      'products.edit_cost',
      'inventory.view',
      'inventory.adjust',
      'inventory.inventory_count',
      'inventory.suppliers',
      'customers.view',
      'customers.edit',
      'customers.contact',
      'customers.export',
      'customers.view_vip',
      'finance.view_revenue',
      'finance.view_costs',
      'finance.view_profit',
      'finance.add_expense',
      'finance.edit_expense',
      'finance.export',
      'marketing.view',
      'marketing.manage_campaigns',
      'marketing.manage_promotions',
      'marketing.manage_creatives',
      'marketing.manage_landing_pages',
      'marketing.manage_affiliates',
      'marketing.manage_seo',
      'marketing.manage_newsletter',
      'marketing.view_analytics',
      'messages.view',
      'messages.reply',
      'reviews.view',
      'reviews.moderate',
      'team.view',
      'team.edit',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'activity.view_all',
      'activity.export',
      'settings.view',
      'settings.edit',
    ],
  },

  // ==========================================
  // 2. OPÉRATIONS & LOGISTIQUE
  // ==========================================
  {
    id: 'OPERATIONS_MANAGER',
    name: 'Responsable des Opérations',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-blue-500/10',
    badgeText: 'text-blue-400',
    badgeBorder: 'border-blue-500/20',
    description: 'Pilotage de la chaîne de commandes, gestion des stocks, expéditions et coordination logistique.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_operations',
      'dashboard.view_support',
      'orders.view',
      'orders.create',
      'orders.edit',
      'orders.change_status',
      'orders.confirm',
      'orders.prepare',
      'orders.cancel',
      'orders.refund',
      'orders.manage_attachments',
      'products.view',
      'inventory.view',
      'inventory.adjust',
      'inventory.inventory_count',
      'inventory.suppliers',
      'customers.view',
      'customers.contact',
      'messages.view',
      'messages.reply',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'activity.view_all',
    ],
  },
  {
    id: 'STOCK_MANAGER',
    name: 'Responsable Stock & Inventaire',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-400',
    badgeBorder: 'border-emerald-500/20',
    description: 'Gestion des niveaux de stocks de testeurs, réassort fournisseurs et comptages physiques.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_operations',
      'products.view',
      'inventory.view',
      'inventory.adjust',
      'inventory.inventory_count',
      'inventory.suppliers',
      'orders.view',
      'orders.prepare',
      'orders.manage_attachments',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'INVENTORY_ASSISTANT',
    name: 'Assistant Stock & Comptage',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-300',
    badgeBorder: 'border-emerald-500/20',
    description: 'Saisie des comptages physiques, vérification des flacons et réceptions.',
    defaultPermissions: [
      'dashboard.view',
      'products.view',
      'inventory.view',
      'inventory.adjust',
      'inventory.inventory_count',
      'orders.manage_attachments',
      'tasks.view',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'ORDER_CONFIRMATION_LEAD',
    name: 'Responsable Confirmation Commandes',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-cyan-500/10',
    badgeText: 'text-cyan-400',
    badgeBorder: 'border-cyan-500/20',
    description: 'Supervision de l\'équipe d\'appels, validation et confirmation téléphonique des commandes.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_operations',
      'dashboard.view_support',
      'orders.view',
      'orders.create',
      'orders.edit',
      'orders.change_status',
      'orders.confirm',
      'orders.cancel',
      'orders.manage_attachments',
      'customers.view',
      'customers.edit',
      'customers.contact',
      'messages.view',
      'messages.reply',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_all',
    ],
  },
  {
    id: 'ORDER_CONFIRMATION_AGENT',
    name: 'Agent de Confirmation Téléphonique',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-cyan-500/10',
    badgeText: 'text-cyan-300',
    badgeBorder: 'border-cyan-500/20',
    description: 'Appels des clients pour validation des adresses, confirmation des commandes et saisie directe.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_operations',
      'orders.view',
      'orders.create',
      'orders.edit',
      'orders.change_status',
      'orders.confirm',
      'orders.cancel',
      'orders.manage_attachments',
      'customers.view',
      'customers.contact',
      'messages.view',
      'messages.reply',
      'tasks.view',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'ORDER_PREPARATION_LEAD',
    name: 'Chef d\'Équipe Préparation & Packaging',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-teal-500/10',
    badgeText: 'text-teal-400',
    badgeBorder: 'border-teal-500/20',
    description: 'Organisation de l\'emballage, étiquetage des colis et remise aux transporteurs.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_operations',
      'orders.view',
      'orders.change_status',
      'orders.prepare',
      'orders.manage_attachments',
      'inventory.view',
      'inventory.adjust',
      'products.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_all',
    ],
  },
  {
    id: 'ORDER_PREPARATION_AGENT',
    name: 'Agent de Préparation & Emballage',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-teal-500/10',
    badgeText: 'text-teal-300',
    badgeBorder: 'border-teal-500/20',
    description: 'Conditionnement soigné des flacons de parfum et préparation des colis.',
    defaultPermissions: [
      'dashboard.view',
      'orders.view',
      'orders.prepare',
      'orders.manage_attachments',
      'inventory.view',
      'products.view',
      'tasks.view',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'SHIPPING_LOGISTICS_COORDINATOR',
    name: 'Coordinateur Logistique & Transport',
    department: 'Opérations & Logistique',
    badgeBg: 'bg-indigo-500/10',
    badgeText: 'text-indigo-400',
    badgeBorder: 'border-indigo-500/20',
    description: 'Suivi des ramassages transporteurs, bordereaux de livraison et résolution des incidents livreur.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_operations',
      'orders.view',
      'orders.change_status',
      'orders.prepare',
      'orders.manage_attachments',
      'inventory.view',
      'customers.view',
      'customers.contact',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },

  // ==========================================
  // 3. SERVICE CLIENT & VENTE
  // ==========================================
  {
    id: 'CUSTOMER_SUPPORT_LEAD',
    name: 'Responsable Service Client',
    department: 'Service Client & Vente',
    badgeBg: 'bg-rose-500/10',
    badgeText: 'text-rose-400',
    badgeBorder: 'border-rose-500/20',
    description: 'Pilotage du support client, gestion des litiges, modération des avis et fidélisation.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_support',
      'orders.view',
      'orders.change_status',
      'orders.confirm',
      'orders.cancel',
      'orders.manage_attachments',
      'customers.view',
      'customers.edit',
      'customers.contact',
      'customers.view_vip',
      'messages.view',
      'messages.reply',
      'reviews.view',
      'reviews.moderate',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_all',
    ],
  },
  {
    id: 'CUSTOMER_SUPPORT_AGENT',
    name: 'Agent Support Client & WhatsApp',
    department: 'Service Client & Vente',
    badgeBg: 'bg-rose-500/10',
    badgeText: 'text-rose-300',
    badgeBorder: 'border-rose-500/20',
    description: 'Réponses aux questions des clients par WhatsApp, formulaires et assistance après-vente.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_support',
      'orders.view',
      'orders.change_status',
      'orders.confirm',
      'orders.manage_attachments',
      'customers.view',
      'customers.contact',
      'messages.view',
      'messages.reply',
      'reviews.view',
      'tasks.view',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'CRM_RETENTION_SPECIALIST',
    name: 'Spécialiste CRM & Fidélisation VIP',
    department: 'Service Client & Vente',
    badgeBg: 'bg-pink-500/10',
    badgeText: 'text-pink-400',
    badgeBorder: 'border-pink-500/20',
    description: 'Animation des clients VIP, relances paniers et programmes de fidélité.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_marketing',
      'dashboard.view_support',
      'customers.view',
      'customers.edit',
      'customers.contact',
      'customers.view_vip',
      'marketing.view',
      'marketing.manage_campaigns',
      'marketing.manage_promotions',
      'marketing.manage_newsletter',
      'orders.view',
      'orders.manage_attachments',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },

  // ==========================================
  // 4. MARKETING & CROISSANCE
  // ==========================================
  {
    id: 'MARKETING_DIRECTOR',
    name: 'Directeur Marketing & Acquisition',
    department: 'Marketing & Croissance',
    badgeBg: 'bg-fuchsia-500/10',
    badgeText: 'text-fuchsia-400',
    badgeBorder: 'border-fuchsia-500/20',
    description: 'Stratégie marketing globale, gestion des budgets publicitaires, campagnes et image de marque.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_marketing',
      'marketing.view',
      'marketing.manage_campaigns',
      'marketing.manage_promotions',
      'marketing.manage_creatives',
      'marketing.manage_landing_pages',
      'marketing.manage_affiliates',
      'marketing.manage_seo',
      'marketing.manage_newsletter',
      'marketing.view_analytics',
      'products.view',
      'customers.view',
      'customers.view_vip',
      'reviews.view',
      'reviews.moderate',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'activity.view_all',
    ],
  },
  {
    id: 'MEDIA_BUYER',
    name: 'Media Buyer & Trafic Ads',
    department: 'Marketing & Croissance',
    badgeBg: 'bg-violet-500/10',
    badgeText: 'text-violet-400',
    badgeBorder: 'border-violet-500/20',
    description: 'Gestion des campagnes TikTok Ads, Meta Ads, Google Ads et analyse des ROAS.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_marketing',
      'marketing.view',
      'marketing.manage_campaigns',
      'marketing.manage_creatives',
      'marketing.manage_landing_pages',
      'marketing.view_analytics',
      'products.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'CONTENT_CREATOR',
    name: 'Créateur de Contenu & Vidéaste UGC',
    department: 'Marketing & Croissance',
    badgeBg: 'bg-amber-500/10',
    badgeText: 'text-amber-300',
    badgeBorder: 'border-amber-500/20',
    description: 'Création de vidéos, photos et créatifs publicitaires pour les parfums.',
    defaultPermissions: [
      'dashboard.view',
      'marketing.view',
      'marketing.manage_creatives',
      'products.view',
      'tasks.view',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'COMMUNITY_MANAGER',
    name: 'Community Manager & Réseaux Sociaux',
    department: 'Marketing & Croissance',
    badgeBg: 'bg-rose-500/10',
    badgeText: 'text-rose-300',
    badgeBorder: 'border-rose-500/20',
    description: 'Animation Instagram, TikTok, publication des visuels et engagement communauté.',
    defaultPermissions: [
      'dashboard.view',
      'marketing.view',
      'marketing.manage_promotions',
      'marketing.manage_creatives',
      'messages.view',
      'messages.reply',
      'reviews.view',
      'reviews.moderate',
      'customers.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'SEO_BLOG_SPECIALIST',
    name: 'Spécialiste SEO & Rédaction Blog',
    department: 'Marketing & Croissance',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-400',
    badgeBorder: 'border-emerald-500/20',
    description: 'Optimisation SEO des pages, rédaction d\'articles de parfumerie et classement Google.',
    defaultPermissions: [
      'dashboard.view',
      'marketing.view',
      'marketing.manage_seo',
      'marketing.manage_landing_pages',
      'marketing.view_analytics',
      'products.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },
  {
    id: 'PRODUCT_CATALOG_MANAGER',
    name: 'Gestionnaire Catalogue & Fiches Parfums',
    department: 'Marketing & Croissance',
    badgeBg: 'bg-orange-500/10',
    badgeText: 'text-orange-400',
    badgeBorder: 'border-orange-500/20',
    description: 'Création et mise à jour des 199 fiches parfums, pyramides olfactives et photos.',
    defaultPermissions: [
      'dashboard.view',
      'products.view',
      'products.create',
      'products.edit',
      'products.edit_price',
      'inventory.view',
      'reviews.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },

  // ==========================================
  // 5. FINANCE & COMPTABILITÉ
  // ==========================================
  {
    id: 'FINANCE_DIRECTOR',
    name: 'Directeur Financier & Comptable',
    department: 'Finance & Comptabilité',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-400',
    badgeBorder: 'border-emerald-500/20',
    description: 'Analyse de rentabilité, suivi du chiffre d\'affaires, gestion des charges et bilans.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_financials',
      'finance.view_revenue',
      'finance.view_costs',
      'finance.view_profit',
      'finance.add_expense',
      'finance.edit_expense',
      'finance.export',
      'orders.view',
      'orders.view_sensitive_financials',
      'orders.manage_attachments',
      'orders.export',
      'products.view',
      'products.edit_cost',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'activity.view_all',
      'activity.export',
    ],
  },
  {
    id: 'ACCOUNTANT',
    name: 'Comptable & Gestionnaire Dépenses',
    department: 'Finance & Comptabilité',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-300',
    badgeBorder: 'border-emerald-500/20',
    description: 'Saisie des dépenses, factures fournisseurs, rapprochements bancaires et exports.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_financials',
      'finance.view_revenue',
      'finance.view_costs',
      'finance.add_expense',
      'finance.edit_expense',
      'finance.export',
      'orders.view',
      'orders.view_sensitive_financials',
      'orders.manage_attachments',
      'orders.export',
      'products.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'activity.view_own',
    ],
  },

  // ==========================================
  // 6. RESSOURCES HUMAINES & IT
  // ==========================================
  {
    id: 'HR_ADMIN',
    name: 'Gestionnaire RH & Équipe',
    department: 'Ressources Humaines & IT',
    badgeBg: 'bg-sky-500/10',
    badgeText: 'text-sky-400',
    badgeBorder: 'border-sky-500/20',
    description: 'Gestion des profils employés, suivi des présences et organisation interne.',
    defaultPermissions: [
      'dashboard.view',
      'team.view',
      'team.create',
      'team.edit',
      'team.change_role',
      'team.disable',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'activity.view_all',
    ],
  },
  {
    id: 'DEVELOPER_IT',
    name: 'Développeur & Administrateur IT',
    department: 'Ressources Humaines & IT',
    badgeBg: 'bg-blue-500/10',
    badgeText: 'text-blue-300',
    badgeBorder: 'border-blue-500/20',
    description: 'Maintenance technique de la plateforme, intégrations API, sécurité et SEO technique.',
    defaultPermissions: [
      'dashboard.view',
      'settings.view',
      'settings.edit',
      'settings.manage_security',
      'marketing.manage_seo',
      'marketing.manage_landing_pages',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'activity.view_all',
    ],
  },

  // ==========================================
  // 7. AUDIT & CONSEIL
  // ==========================================
  {
    id: 'AUDITOR_CONSULTANT',
    name: 'Auditeur Externe / Consultant',
    department: 'Audit & Conseil',
    badgeBg: 'bg-zinc-500/10',
    badgeText: 'text-zinc-400',
    badgeBorder: 'border-zinc-500/20',
    description: 'Accès en lecture seule complète pour audit financier, logistique et commercial.',
    defaultPermissions: [
      'dashboard.view',
      'dashboard.view_financials',
      'dashboard.view_operations',
      'dashboard.view_marketing',
      'dashboard.view_support',
      'orders.view',
      'orders.view_sensitive_financials',
      'orders.manage_attachments',
      'orders.export',
      'products.view',
      'inventory.view',
      'customers.view',
      'customers.export',
      'finance.view_revenue',
      'finance.view_costs',
      'finance.view_profit',
      'finance.export',
      'marketing.view',
      'marketing.view_analytics',
      'activity.view_all',
      'activity.export',
    ],
  },
  {
    id: 'GUEST_VIEWER',
    name: 'Invité & Stagiaire (Accès Restreint)',
    department: 'Audit & Conseil',
    badgeBg: 'bg-zinc-500/10',
    badgeText: 'text-zinc-500',
    badgeBorder: 'border-zinc-500/20',
    description: 'Accès de découverte minimal sans visibilité sur les données sensibles.',
    defaultPermissions: [
      'dashboard.view',
      'products.view',
      'tasks.view',
      'activity.view_own',
    ],
  },
];

export const ROLE_MAP = new Map<string, RoleDefinition>(
  ALL_ROLES.map((r) => [r.id, r])
);

/**
 * Get role definition by ID with graceful fallback for legacy roles
 */
export function getRoleDefinition(roleId: string | null | undefined): RoleDefinition {
  if (!roleId) return ROLE_MAP.get('GUEST_VIEWER')!;
  
  // Normal lookup
  const found = ROLE_MAP.get(roleId.toUpperCase());
  if (found) return found;

  // Handle legacy roles
  if (roleId === 'SUPER_ADMIN' || roleId === 'ADMIN' || roleId === 'OWNER') {
    return ROLE_MAP.get('OWNER')!;
  }

  return {
    id: roleId,
    name: roleId,
    department: 'Direction & Fondateurs',
    badgeBg: 'bg-zinc-500/10',
    badgeText: 'text-zinc-400',
    badgeBorder: 'border-zinc-500/20',
    description: 'Rôle personnalisé',
    defaultPermissions: ['dashboard.view'],
  };
}
