const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/lib/products.ts');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Update Brand Type
content = content.replace(
  "export type Brand = 'valentino' | 'yves-saint-laurent' | 'armani';",
  "export type Brand = 'valentino' | 'yves-saint-laurent' | 'armani' | 'dolce-gabbana' | 'burberry' | 'prada';"
);

// 2. Add Products
const newProducts = `    inStock: true,
  },
  {
    id: 401,
    slug: 'dolce-gabbana-limperatrice',
    name: "L'Impératrice",
    brand: 'dolce-gabbana',
    brandLabel: 'Dolce & Gabbana',
    gender: 'women',
    subcategory: 'fresh',
    subcategoryLabel: 'Fresh',
    tagline: 'Vibrant and magnetic',
    price: 1150,
    description: 'Une fragrance fruitée et florale captivante, combinant kiwi, rhubarbe et pastèque.',
    longDescription: "L'Impératrice de Dolce & Gabbana est un parfum joyeux, éclatant et délicieusement addictif. Une eau de toilette emblématique qui célèbre la vivacité et le charisme.",
    images: ['/images/dg_imperatrice.png'],
    notes: { top: ['Kiwi', 'Rhubarb', 'Pink Pepper'], heart: ['Watermelon', 'Cyclamen', 'Jasmine'], base: ['Lemon Tree', 'Sandalwood', 'Musk'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '100ml', ml: 100, price: 1150 }],
    bottleColor: 'clear',
    bottleColorLabel: 'Transparent',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre pur',
    rating: 4.6,
    reviewCount: 312,
    releaseDate: '2020-01-01',
    tags: ['bestseller'],
    inStock: true,
  },
  {
    id: 402,
    slug: 'burberry-her-intense',
    name: 'Her Eau de Parfum Intense',
    brand: 'burberry',
    brandLabel: 'Burberry',
    gender: 'women',
    subcategory: 'floral',
    subcategoryLabel: 'Floral',
    tagline: 'Bold and London-spirited',
    price: 1650,
    description: "Une version intense aux notes de fruits rouges assombries par le jasmin et l'ambre chaud.",
    longDescription: "Burberry Her Intense capture l'énergie frénétique de Londres. Une explosion de fruits rouges sublimée par des notes florales intenses et un fond chaleureux d'ambre et de benjoin.",
    images: ['/images/burberry_her.png'],
    notes: { top: ['Blackberry', 'Red Fruits'], heart: ['Jasmine'], base: ['Benzoin', 'Amber', 'Cedar'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '100ml', ml: 100, price: 1650 }],
    bottleColor: 'pink',
    bottleColorLabel: 'Rose Poudré',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre opaque',
    rating: 4.8,
    reviewCount: 410,
    releaseDate: '2021-01-01',
    tags: ['new-arrival'],
    inStock: true,
  },
  {
    id: 403,
    slug: 'prada-paradigme',
    name: 'Paradigme Milano',
    brand: 'prada',
    brandLabel: 'Prada',
    gender: 'unisex',
    subcategory: 'woody',
    subcategoryLabel: 'Woody',
    tagline: 'Avant-garde and timeless',
    price: 1800,
    description: 'Une expression boisée et aromatique avec une touche moderne signature de Prada Milano.',
    longDescription: "Un parfum d'avant-garde qui défie les conventions. Sa teinte verte émeraude cache un sillage boisé et riche, parfait pour ceux qui recherchent l'unicité.",
    images: ['/images/prada_green.png'],
    notes: { top: ['Bergamot', 'Green Notes'], heart: ['Iris', 'Cardamom'], base: ['Vetiver', 'Sandalwood', 'Musk'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '100ml', ml: 100, price: 1800 }],
    bottleColor: 'green',
    bottleColorLabel: 'Vert Émeraude',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre teinté',
    rating: 4.7,
    reviewCount: 205,
    releaseDate: '2023-01-01',
    tags: ['staff-pick'],
    inStock: true,
  },
  {
    id: 404,
    slug: 'valentino-donna-intense',
    name: 'Donna Born in Roma Intense',
    brand: 'valentino',
    brandLabel: 'Valentino',
    gender: 'women',
    subcategory: 'oriental',
    subcategoryLabel: 'Oriental',
    tagline: "A tribute to Rome's vibrant energy",
    price: 1550,
    description: 'Une infusion de vanille bourbon et de jasmin pour une intensité florale couture.',
    longDescription: "Donna Born in Roma Intense amplifie l'addiction de la fragrance originale avec une double dose de vanille bourbon, poussant la sensualité florale à son apogée.",
    images: ['/images/valentino_donna_intense.png'],
    notes: { top: ['Vanilla Bourbon'], heart: ['Jasmine Grandiflorum'], base: ['Benzoin Resin'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '100ml', ml: 100, price: 1550 }],
    bottleColor: 'black',
    bottleColorLabel: 'Noir Clouté',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre clouté',
    rating: 4.9,
    reviewCount: 520,
    releaseDate: '2026-07-01', // Make it show as new arrival
    tags: ['bestseller', 'new-arrival'],
    inStock: true,
  },
  {
    id: 405,
    slug: 'armani-my-way-floral',
    name: 'My Way Parfum',
    brand: 'armani',
    brandLabel: 'Giorgio Armani',
    gender: 'women',
    subcategory: 'floral',
    subcategoryLabel: 'Floral',
    tagline: 'An intense floral woody powder',
    price: 1350,
    description: "L'intensité de l'iris pallida et de la tubéreuse dans un sillage ambré boisé enchanteur.",
    longDescription: "My Way Parfum révèle une nouvelle facette plus poudrée et intense. L'iris bleu éclatant rencontre la tubéreuse crémeuse sur un fond chaleureux de vanille et bois de cèdre.",
    images: ['/images/armani_my_way.png'],
    notes: { top: ['Orange Blossom', 'Bitter Orange'], heart: ['Iris Pallida', 'Tuberose'], base: ['Cedarwood', 'Vanilla Bourbon', 'White Musk'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '90ml', ml: 90, price: 1350 }],
    bottleColor: 'pink',
    bottleColorLabel: 'Rose Poudré',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre pur',
    rating: 4.8,
    reviewCount: 395,
    releaseDate: '2026-07-02', // Make it show as new arrival
    tags: ['new-arrival'],
    inStock: true,
  }
];`;

content = content.replace(/    inStock: true,\n  },\n];/m, newProducts);

// 3. Add Brands
const newBrands = `    origin: 'Milan, Italie',
  },
  {
    key: 'dolce-gabbana',
    label: 'Dolce & Gabbana',
    slug: 'dolce-gabbana',
    tagline: "L'esprit flamboyant de la Sicile",
    description: 'Dolce & Gabbana célèbre le glamour italien. Leurs créations olfactives expriment une passion méditerranéenne inégalée.',
    heroImage: 'https://images.pexels.com/photos/11216321/pexels-photo-11216321.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600',
    founded: 1985,
    origin: 'Milan, Italie',
  },
  {
    key: 'burberry',
    label: 'Burberry',
    slug: 'burberry',
    tagline: "L'élégance britannique intemporelle",
    description: "Burberry capture l'esprit de Londres. Des fragrances sophistiquées qui mêlent l'audace contemporaine à l'héritage anglais.",
    heroImage: 'https://images.pexels.com/photos/7850600/pexels-photo-7850600.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600',
    founded: 1856,
    origin: 'Londres, Royaume-Uni',
  },
  {
    key: 'prada',
    label: 'Prada',
    slug: 'prada',
    tagline: "L'avant-garde intellectuelle",
    description: 'Prada réinvente la parfumerie avec une approche intellectuelle et avant-gardiste. Des compositions inattendues, minimalistes et luxueuses.',
    heroImage: 'https://images.pexels.com/photos/36834014/pexels-photo-36834014.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600',
    founded: 1913,
    origin: 'Milan, Italie',
  }
] as const;`;

content = content.replace(/    origin: 'Milan, Italie',\n  },\n\] as const;/m, newBrands);

fs.writeFileSync(filePath, content);
console.log("Successfully updated products catalog");
