const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/lib/products.ts');
let content = fs.readFileSync(filePath, 'utf8');

const mensProducts = `    inStock: true,
  },
  {
    id: 501,
    slug: 'ysl-y-edp',
    name: 'Y Eau de Parfum',
    brand: 'yves-saint-laurent',
    brandLabel: 'Yves Saint Laurent',
    gender: 'men',
    subcategory: 'woody',
    subcategoryLabel: 'Boisé',
    tagline: 'The scent of accomplishment',
    price: 1250,
    description: 'Un parfum fougère boisé profond, intense et masculin.',
    longDescription: "Y Eau de Parfum représente l'homme accompli qui a réalisé ses rêves. Une fragrance boisée intense où l'accord frais de la sauge et de la pomme rencontre la profondeur du bois de cèdre.",
    images: ['https://images.pexels.com/photos/1961795/pexels-photo-1961795.jpeg?auto=compress&cs=tinysrgb&w=800'],
    notes: { top: ['Apple', 'Ginger', 'Bergamot'], heart: ['Sage', 'Juniper Berries', 'Geranium'], base: ['Amberwood', 'Tonka Bean', 'Cedar'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '100ml', ml: 100, price: 1250 }],
    bottleColor: 'black',
    bottleColorLabel: 'Noir Fumé',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre lourd',
    rating: 4.9,
    reviewCount: 840,
    releaseDate: '2018-01-01',
    tags: ['bestseller'],
    inStock: true,
  },
  {
    id: 502,
    slug: 'armani-acqua-di-gio-parfum',
    name: 'Acqua Di Giò Parfum',
    brand: 'armani',
    brandLabel: 'Giorgio Armani',
    gender: 'men',
    subcategory: 'aromatic',
    subcategoryLabel: 'Aromatique',
    tagline: 'Deep oceanic freshness',
    price: 1400,
    description: 'Une nouvelle intensité mystérieuse et aquatique.',
    longDescription: "Acqua Di Giò Parfum apporte une dimension plus intense et boisée à la signature marine originelle. Un parfum d'une fraîcheur puissante et incandescente.",
    images: ['https://images.pexels.com/photos/935985/pexels-photo-935985.jpeg?auto=compress&cs=tinysrgb&w=800'],
    notes: { top: ['Marine Notes', 'Bergamot'], heart: ['Rosemary', 'Clary Sage', 'Geranium'], base: ['Patchouli', 'Incense'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '100ml', ml: 100, price: 1400 }],
    bottleColor: 'black',
    bottleColorLabel: 'Noir Mat',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre mat',
    rating: 4.8,
    reviewCount: 520,
    releaseDate: '2023-01-01',
    tags: ['bestseller', 'new-arrival'],
    inStock: true,
  },
  {
    id: 503,
    slug: 'armani-code-parfum',
    name: 'Armani Code Parfum',
    brand: 'armani',
    brandLabel: 'Giorgio Armani',
    gender: 'men',
    subcategory: 'woody',
    subcategoryLabel: 'Boisé',
    tagline: 'Rewrite the code',
    price: 1350,
    description: 'Une réécriture forte et sensible du parfum classique.',
    longDescription: "Armani Code Parfum offre une signature olfactive vibrante grâce à son cœur d'Iris éclatant, tout en conservant l'identité boisée et ambrée originelle.",
    images: ['https://images.pexels.com/photos/1961792/pexels-photo-1961792.jpeg?auto=compress&cs=tinysrgb&w=800'],
    notes: { top: ['Bergamot', 'Bergamot Leaf'], heart: ['Iris', 'Clary Sage', 'Aldehydes'], base: ['Tonka Bean', 'Cedar'] },
    ingredients: 'Alcohol, Parfum, Aqua...',
    sizes: [{ label: '125ml', ml: 125, price: 1350 }],
    bottleColor: 'black',
    bottleColorLabel: 'Noir Élégant',
    bottleMaterial: 'glass',
    bottleMaterialLabel: 'Verre rechargeable',
    rating: 4.7,
    reviewCount: 310,
    releaseDate: '2022-01-01',
    tags: [],
    inStock: true,
  }
];`;

content = content.replace(/    inStock: true,\n  },\n\];/m, mensProducts);

fs.writeFileSync(filePath, content);
console.log("Men's products added");
